### ISSUE TITLE
What Machince

### ISSUE THREAD

**Issue by SudashD** [citrix/en-us-tech-zone#1101]
What domain joined VM? 
"Step 3: Enable Azure Files AD Authentication

Use the instructions in this section to enable Azure Files AD Authentication on a machine that’s already domain-joined.

    Use Remote Desktop Protocol (RDP) to connect to the domain-joined virtual machine."

Can I use the Gold Image with the VDA installed? If I push out the update to the other VDI will it cause issues?
Does the Machine have to be power on at all times? 

https://docs.citrix.com/en-us/tech-zone/build/deployment-guides/citrix-azure-files.html

**Comment by loaycitrix** [comment]
hello, you can "Enable Azure Files Ad Authentication" from any machines that is domain joined. It is a one time task that needs to be run. The VM doesn't need to exist after you run the instructions. Hope that answers the question.

**Comment by SudashD** [comment]
Perfect, thank you

Sent from Nine
________________________________
