### ISSUE TITLE
Link requested/expected

### ISSUE THREAD

**Issue by rickd4real** [citrix/en-us-tech-zone#1259]
The following line in the doc references an external resource: consider adding a link to the reference:
"To gain a deeper understanding of the primary identity for Citrix Workspace, refer to the **Workspace Identity Tech Brief**."

https://docs.citrix.com/en-us/tech-zone/learn/tech-briefs/workspace-sso.html

**Comment by martinzugec-ctx** [comment]
Good catch @rickd4real, thanks! Link updated, it just went live
