### ISSUE TITLE
Antivirus exclusions for Cloud Connectors

### ISSUE THREAD

**Issue by jessez123** [citrix/en-us-tech-zone#1323]
Wondering if the exclusion list for Cloud connectors is incomplete as there are WEM services that run on a Cloud Connector (https://docs.citrix.com/en-us/citrix-cloud/citrix-cloud-resource-locations/citrix-cloud-connector/technical-details.html#cloud-connector-installed-services) that are not listed in the antivirus exclusions of the Cloud Connector.

https://docs.citrix.com/en-us/tech-zone/build/tech-papers/antivirus-best-practices.html

**Comment by martinzugec-ctx** [comment]
@jessez123 Just confirmed with WEM team, it is not needed to exclude any WEM components on cloud connectors. As a general rule, we try to keep exclusions to minimum, excluding only files/processes that are known to cause performance an/or stability issues.

**Comment by jessez123** [comment]
Thank you!

Jesse Zilberman | M: +1 561-281-5184 | jesse.zilberman@citrix.com<mailto:jesse.zilberman@citrix.com>
