### ISSUE TITLE
Update Resource Group Limits Based on (https://www.citrix.com/blogs/2020/10/19/single-resource-group-support-available-for-citrix-mcs-on-azure)

### ISSUE THREAD

**Issue by skleinert** [citrix/en-us-tech-zone#1501]
https://docs.citrix.com/en-us/tech-zone/design/reference-architectures/virtual-apps-and-desktops-azure.html

**Comment by loaycitrix** [comment]
updated and removed the 240/800 limit per resource group

**Comment by martinzugec-ctx** [comment]
Released to production, thanks for reporting this 👍
