### ISSUE TITLE
Update link in article

### ISSUE THREAD

**Issue by amccullough84** [citrix/en-us-tech-zone#1512]
https://docs.citrix.com/en-us/tech-zone/learn/tech-briefs/zero-trust.html

In the Guiding Principles section, the link to the NIST Zero Trust tenets goes to a withdrawn draft. It has been superseded by this: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-207.pdf which is the published final version.

**Comment by martinzugec-ctx** [comment]
Good catch, I've updated URL to final draft, change should be live in ~10 minutes. 

Thanks Andy!
