### ISSUE TITLE
Description for CWA to VDA correct?

### ISSUE THREAD

**Issue by RasmusRaunNielsen25** [citrix/en-us-tech-zone#1552]
(Source, Dest., Type, Port, Description)

Citrix Workspace app | Virtual Delivery Agent | TCP | 80, 443 | Communication with StoreFront

Is Description correct?

https://docs.citrix.com/en-us/tech-zone/build/tech-papers/citrix-communication-ports.html

**Comment by martinzugec-ctx** [comment]
Thanks @RasmusRaunNielsen25 ! Fixed description, updating in production now
