### ISSUE TITLE
Omission of Desktop OS VDA for Session Recording

### ISSUE THREAD

**Issue by mshuster-ctx** [citrix/en-us-tech-zone#1555]
Session Recording ports only indicate Server OS VDA when Windows 10 is supported.
https://docs.citrix.com/en-us/session-recording/1912-ltsr/system-requirements.html#session-recording-agent

Warrants being updated.

https://docs.citrix.com/en-us/tech-zone/build/tech-papers/citrix-communication-ports.html

**Comment by martinzugec-ctx** [comment]
Thanks @mshuster-ctx ! Fixed description and updating in production now, we have started to clean up this article
