### ISSUE TITLE
ADC to ADM for Pooled Licensing

### ISSUE THREAD

**Issue by cstalhood** [citrix/en-us-tech-zone#1671]
In the ADM table, should there be rules from ADC NSIP to ADM on ports 27000 and 7279? I see a rule from ADM to CPX, which seems backwards.

https://docs.citrix.com/en-us/tech-zone/build/tech-papers/citrix-communication-ports.html

**Comment by martinzugec-ctx** [comment]
Thanks for reporting this Carl! Fixing it right now, you are right, these rules are reversed
