### ISSUE TITLE
Re-word needed. 

### ISSUE THREAD

**Issue by Prabhjotsb** [citrix/en-us-tech-zone#1672]
https://docs.citrix.com/en-us/tech-zone/design/reference-architectures/access-control.html

This sentence does not make sense: "The “unknown” category of websites on the internet and presenting a user with a single portal for SaaS and virtual apps. "

**Comment by martinzugec-ctx** [comment]
Article update just went live, thanks for your feedback and helping us to make Tech Zone better!
