### ISSUE TITLE
Need to update App Layering AWS support statement

### ISSUE THREAD

**Issue by daniellaza** [citrix/en-us-tech-zone#1758]
Hello Doc team!

I am the PM for App Layering and would like to request a change to our App Layering and AWS support statement in this article.

Please update the following paragraph in this document relating to App Layering support for AWS:
One final word on application design, and something existing Citrix customers who have adopted or are adopting Citrix App Layering technology must know: App Layering, in the formal sense, does not currently support AWS. The Enterprise Layer Manager appliance does not currently run on AWS, and does not currently support exporting layered images into an immediately consumable disk format for use on AWS. It is technically possible to export a layered image to another format (like VMDK), then import and convert a layered image into a usable Amazon Machine Image (AMI), however this process is unsupported. If App Layering support on AWS is critical for your migration or deployment, email aws@citrix.com with information about your project. You’ll be added to the list to be an early adopter candidate for future releases, and your voice will be heard. For more information on Citrix App Layering, refer to the product documentation and App Layering reference architecture.

To this:
One final word on application design, the Enterprise Layer Manager appliance does not currently run on AWS, and does not currently support exporting layered images into an immediately consumable disk format for use on AWS. If App Layering support on AWS is critical for your migration or deployment, email aws@citrix.com with information about your project. You’ll be added to the list to be an early adopter candidate for future releases, and your voice will be heard. For more information on Citrix App Layering, refer to the product documentation and App Layering reference architecture.

Thank you and please reach out to me directly with any questions/concerns.
- Dan Lazar

https://docs.citrix.com/en-us/tech-zone/design/reference-architectures/citrix-virtual-apps-and-desktops-on-aws.html

**Comment by martinzugec-ctx** [comment]
@daniellaza Done! I was just fixing some link in that article, so included your change (should be live in few minutes)
