### ISSUE TITLE
StoreFront fall back - No PS commands mentioned

### ISSUE THREAD

**Issue by skleinert** [citrix/en-us-tech-zone#1764]
Hi There, 

StoreFront Fall back is mentioned and note about Powershell command to enable this, and provide the URL but no reference of the command. Can we have this added. This is a newer feature with no reference in the documentation. Please also have some documentation around this feature as well. 

"Admins, using PowerShell, can define a fallback StoreFront HTTP(S) URL, that resolves to an internal StoreFront or an external Citrix Gateway server."

https://docs.citrix.com/en-us/tech-zone/learn/tech-briefs/citrix-cloud-resiliency.html

**Comment by BadgerBadgerAndFox** [comment]
bump...

No amount of googlefu has revealed how this is configured. Please update the documentation.

**Comment by martinzugec-ctx** [comment]
This is in a private tech preview at the moment - we've updated the verbiage to better reflect that, thanks Shane for reporting it! Public documentation is typically not ready until at least public tech preview (or until service reaches GA).
