### ISSUE TITLE
Fallback to Storefront should be identified as TP

### ISSUE THREAD

**Issue by josecitrix** [citrix/en-us-tech-zone#1843]
Fallback to Storefront is in Pvt. TP. We should add the (Tech Preview) tag to the title to manage expectations. I had a customer reach out asking about link to the POSH documentation to enable the feature!

https://docs.citrix.com/en-us/tech-zone/learn/tech-briefs/citrix-cloud-resiliency.html

**Comment by martinzugec-ctx** [comment]
Updated article with tech preview disclaimer
