### ISSUE TITLE
%ProgramFiles(x86)%\Citrix\ICA Client\HdxTeams.exe exclusion is incorrect

### ISSUE THREAD

**Issue by JonathanPitre** [citrix/en-us-tech-zone#1881]
According to this article
https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/multimedia/opt-ms-teams.html

The WebRTC media engine in Workspace app for Windows 2009.6 and Linux 2009 is renamed from HdxTeams.exe to HdxRtcEngine.exe

Therefore the antivirus exclusions should be updated to reflect that change
https://docs.citrix.com/en-us/tech-zone/build/tech-papers/antivirus-best-practices.html

%ProgramFiles(x86)%\Citrix\ICA Client\HdxTeams.exe (Optimization for Microsoft Teams for Workspace App 2009.5 and lower)
%ProgramFiles(x86)%\Citrix\ICA Client\HdxTeams.exe (Optimization for Microsoft Teams for Workspace App 2009.6 and above)

I also verified on my machine and HdxTeams.exe no longer exist.

Please update the article accordiingly,

**Comment by martinzugec-ctx** [comment]
Thanks @JonathanPitre, fixed!
