### ISSUE TITLE
Add link to the docs article on Autoscale and Tags (Cloud Burst)

### ISSUE THREAD

**Issue by ricoprojer** [citrix/en-us-tech-zone#1896]
Under https://docs.citrix.com/en-us/tech-zone/learn/tech-briefs/autoscale.html#cloud-deployment-with-reserved-and-pay-as-you-go-instances you mention: "For more information, see Zone Preference and Tags" but there is no link to the actual doc article on how to configure Autoscale to adhere to tags. 

Can you add a link to https://docs.citrix.com/en-us/citrix-virtual-apps-desktops-service/manage-deployment/autoscale/restrict-autoscale.html please?

Thanks a lot in advance and regards

--Rico

**Comment by ricoprojer** [comment]
Or just add the Powershell commands to the article...

**Comment by martinzugec-ctx** [comment]
Thanks @ricoprojer for feedback. Just updated the article, should go live later today with other changes 👍

**Comment by ricoprojer** [comment]
Thanks Martin!
