### ISSUE TITLE
What happened to the original CVADS RA? Did we just remove all that info?

### ISSUE THREAD

**Issue by AllenF817** [citrix/en-us-tech-zone#1913]
https://docs.citrix.com/en-us/tech-zone/design/reference-architectures/virtual-apps-and-desktops-service.html

**Comment by martinzugec-ctx** [comment]
Hi @AllenF817,

Information in older RA has been updated, but original content is still available in GitHub versioning (we never completely discard anything that is released in Tech Zone).

**Comment by AllenF817** [comment]
The article is half the length it used to be with no deployment scenarios and more limited info. I don't even see this update listed in the Tech Zone document history which is concerning.
