### ISSUE TITLE
Citrix Virtual Apps and Desktop Service Ports Clarification

### ISSUE THREAD

**Issue by r-ali** [citrix/en-us-tech-zone#1954]
Hello. It would be beneficial to add required ports 1494/2598 for Citrix Virtual Apps and Desktops Service section as outlined below. The article does not explicitly define this and it is important to mention this to remove any ambiguity. 

Source: Cloud Connectors - Destination: Virtual Delivery Agents - Type: TCP, UDP.

https://docs.citrix.com/en-us/tech-zone/build/tech-papers/citrix-communication-ports.html

**Comment by martinzugec-ctx** [comment]
@r-ali Thanks for feedback. You are right, these ports are missing and should be included, I've just updated table and added them 👍
