### ISSUE TITLE
From a Citrite, do we have access to the sources for the images in this doc?

### ISSUE THREAD

**Issue by B3arPaw** [citrix/en-us-tech-zone#1977]
https://docs.citrix.com/en-us/tech-zone/design/reference-architectures/virtual-apps-and-desktops-azure.html

**Comment by martinzugec-ctx** [comment]
Let me talk to original author - if we have those source diagrams, we will upload them for everyone to use 👍

**Comment by martinzugec-ctx** [comment]
@B3arPaw Got some good news - source diagrams have been added to the article, just look for "**Sources**" section.
