### ISSUE TITLE
FSLogix

### ISSUE THREAD

**Issue by AtumVirt** [citrix/en-us-tech-zone#2021]
Given the prevalence of FSLogix in Citrix environments, it would be a good idea to at least mention it in the article and provide a link or list of AV exclusions.

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix

https://docs.citrix.com/en-us/tech-zone/build/tech-papers/antivirus-best-practices.html

**Comment by martinzugec-ctx** [comment]
Article update just went live, thanks Preston for your feedback and helping us to make Tech Zone better!
