### ISSUE TITLE
SSD spelt wront

### ISSUE THREAD

**Issue by mshuster-ctx** [citrix/en-us-tech-zone#2087]
What impact does the Machine Creation Services I/O cache have?
Under that section header when referring to SSD and HDD, SSD is spelled SDD.

https://docs.citrix.com/en-us/tech-zone/design/design-decisions/azure-instance-scalability.html

**Comment by martinzugec-ctx** [comment]
Article update just went live, thanks Michael for your feedback and helping us to make Tech Zone better!
