### ISSUE TITLE
Correcting grammar

### ISSUE THREAD

**Issue by mshuster-ctx** [citrix/en-us-tech-zone#2352]
The phrase:
Do we must host critical workloads only (that is, subset of production)?

Can this get corrected? I suspect this was an Acrolynx mishap.

https://docs.citrix.com/en-us/tech-zone/design/design-decisions/cvad-disaster-recovery.html

**Comment by martinzugec-ctx** [comment]
@mshuster-ctx Sorry it took so long, just reviewed all Acrolinx changes and fixed everything that didn't translate correctly 👍
