### ISSUE TITLE
Required changes to the documentation

### ISSUE THREAD

**Issue by sakthigj** [citrix/en-us-tech-zone#954]
From https://docs.citrix.com/en-us/tech-zone/design/design-decisions/hdx-graphics.html , HDX Graphics overview section: 

I would suggest reviewing the punctuation marks again in the following sentence. Also, even though the text says 3 types, the information below lists four types. If Text, Simple images and Solid colors are considered as one single group, its better to list them as such rather than listing them separately.

"As we deliver graphic content for applications or desktops the HDX graphics encoding engine, Thinwire, dynamically categorizes display data into three types:"

"Choosing to Configure Thinwire to use the Codec For the Entire Screen tell Thinwire" should be "Choosing to Configure Thinwire to use the Codec For the Entire Screen tell**s** Thinwire"

Full stops missing in the following sections:

"As illustrated below, H.264 / H.265 is “Inactive” until regions of fluid movement are detected The VDA then transitions to H.264 / H.265 to encode the selected region during fluid movement and returns to an “Inactive” state once the selected region no longer contains fluid content."

"Configuring Thinwire to use the Video Codec for the Entire Screen is designed for the heavy multimedia use-case, where larger regions of the screen are in motion Higher compression and quality is achieved at the expense of CPU and server scalability."

"The CPU can quickly become a bottleneck, if undersized, resulting in poor performance and user experience under heavy multimedia conditions Consider GPU offload capabilities to supplement this graphics mode while using these application types."

"By default, all processing for encoding graphics occurs within the CPU on the VDA AMD, Intel, and NVIDIA graphics cards are currently supported to offload encoding to the GPU before being sent to your endpoint for decoding."

Consider rephrasing / correcting the following sentence:

"The Use Video Codec for Compression is the main policy to configure Thinwire to Not Use Video Codec (Adaptive JPEG), For Actively Changing Regions (Selective H.264/H.265), or Thinwire for the Entire Screen (Full Screen H.264/H.265)."

**Comment by martinzugec-ctx** [comment]
I've contacted original author and we are going to fix these issues.

Thanks @sakthigj!

**Comment by martinzugec-ctx** [comment]
@ricoprojer

**Comment by martinzugec-ctx** [comment]
Thanks @sakthigj for helping us to make Citrix Tech Zone better! Rico has just updated the article with your suggestions, changes went live few minutes ago
